### ISSUE TITLE
Sometimes table creations prints messages to std err

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/mysql#3] opened 2015-02-26 20:38 UTC
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymysql/cursors.py:127: Warning: Table 'table_name' already exists
  result = self._query(query)

Steps to reproduce:
Create a service with two simulators that write to the same mysql_insert block. Make sure they go to the same table.

**Comment by tyoungNIO** [comment] 2018-07-30 21:06
This looks like it is no longer applicable, closing this issue until it can be reproduced.

**Closed by tyoungNIO** 2018-07-30 21:06 UTC
